services:
  app:
    build:
      dockerfile: backend/Dockerfile
      context: ..
    image: jhj0517/whisper-webui-backend:latest

    volumes:
      # You can mount the container's volume paths to directory paths on your local machine.
      # Models will be stored in the `./models' directory on your machine.
      # Similarly, all output files will be stored in the `./outputs` directory.
      # The DB file is saved in /Whisper-WebUI/backend/records.db unless you edit it in /Whisper-WebUI/backend/configs/.env
      - /Whisper-WebUI/models
      - /Whisper-WebUI/outputs

    ports:
      - "8000:8000"

    stdin_open: true
    tty: true

    entrypoint: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
