services:
  app:
    build:
      dockerfile: backend/Dockerfile
      context: ..
    image: jhj0517/whisper-webui-backend:latest


    ports:
      - "8000:8000"

    stdin_open: true
    tty: true

    entrypoint: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]

    # If you're not using Nvidia GPU, Update device to match yours.
    # See more info at : https://docs.docker.com/compose/compose-file/deploy/#driver
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]